apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: instant-ostrich-go 
  janus-idp.io/tekton: instant-ostrich-go
  backstage.io/kubernetes-id: instant-ostrich-go
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: instant-ostrich-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  